{
 "title": "SFTPGo",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(sftpgo_active_connections, namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(sftpgo_active_connections, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sftpgo_active_connections{namespace=~\"$namespace\",job=~\"$job\"}"
    }
   ]
  },
  { "title": "Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Logins",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_login_attempts_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "login attempts ({{job}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_login_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "login Ok ({{job}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "login Fail ({{job}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_no_auth_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "login No Auth ({{job}})"
    }
   ]
  },
  {
   "title": "Password Logins",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_password_login_attempts_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "attempts ({{job}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_password_login_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "Ok ({{job}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_password_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "Fail ({{job}})"
    }
   ]
  },
  {
   "title": "Public Key Logins",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_public_key_login_attempts_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "attempts ({{job}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_public_key_login_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "Ok ({{job}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_public_key_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "Fail ({{job}})"
    }
   ]
  },
  {
   "title": "TLS & Passwd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_tls_cert_and_pwd_login_attempts_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "attempts ({{job}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_tls_cert_and_pwd_login_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "Ok ({{job}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_tls_cert_and_pwd_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "Fail ({{job}})"
    }
   ]
  },
  {
   "title": "TLS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_tls_cert_login_attempts_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "attempts ({{job}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_tls_cert_login_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "Ok ({{job}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_tls_cert_login_ko_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "Fail ({{job}})"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(sftpgo_http_req_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "Requests All ({{job}})"
    },
    {
     "expr": "sum by (job) (rate(sftpgo_http_req_ok_total{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "Requests Ok ({{job}})"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sftpgo_http_client_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m])",
     "legendFormat": "Client errors"
    },
    {
     "expr": "rate(sftpgo_http_server_errors_total{namespace=~\"$namespace\",job=~\"$job\"}[1m])",
     "legendFormat": "Server errors"
    }
   ]
  }
 ]
}